# Generated by Django 5.2 on 2025-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="session id"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="url"
            ),
        ),
    ]
