version: "2.35.0"

services:

  db:
    image: postgres:14.6-alpine
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: .
    command: > 
      sh -c "celery -A hw24_1 worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      app:
        condition: service_started

  celery_beat:
    build:
      context: .
    command: >
      sh -c "celery -A hw24_1 beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      app:
        condition: service_started
